version: "3.8"

services:
  redis:
    image: redis:6-alpine
    container_name: nitter-redis
    restart: always

  nitter:
    image: zedeus/nitter:latest
    container_name: nitter
    restart: always
    depends_on:
      - redis
    ports:
      - "8099:8080"
    volumes:
      - ./nitter.conf:/src/nitter.conf:ro
      - ./sessions.jsonl:/src/sessions.jsonl:ro
